Добавлены методы для случайного целого числа и проверки длины строки
htmlacademy-univer-javascript-1/1920307-kekstagram-1 pull request #3
Opened 2022-09-20 15:30 UTC by cutterror

2022-09-21 14:38 UTC, pavel-nyukalo requested changes

2022-09-21 14:38 UTC, pavel-nyukalo commented on js/main.js
> +function getRandomIntNumber(min, max) {
Необходимо поправить ошибки линтера

2022-09-22 09:35 UTC, cutterror commented
Поправила, добавив "заглушки"

2022-09-22 09:50 UTC, pavel-nyukalo requested changes

2022-09-22 09:50 UTC, pavel-nyukalo commented on js/main.js
> +checkLength();
Функции у нас принимают параметры (min, max в первой и string, maxLenght во второй), поэтому при вызове необходимо передать эти параметры, например `getRandomIntNumber(10, 50)`

2022-09-23 16:07 UTC, cutterror commented
Добавила в вызов функций аргументы

2022-09-24 16:43 UTC, pavel-nyukalo approved these changes

2022-09-24 16:43 UTC, merged