сгенерировала данные, выполнив 4.15
htmlacademy-univer-javascript-1/1920307-kekstagram-1 pull request #4
Opened 2022-10-04 17:01 UTC by cutterror

2022-10-12 14:26 UTC, pavel-nyukalo requested changes

2022-10-12 14:26 UTC, pavel-nyukalo commented on js/main.js
> +  const commentsCount = getRandomIntNumber(2, 5);
2 и 5 считаются магическими числами, для них нужно завести переменные

2022-10-12 14:26 UTC, pavel-nyukalo commented on js/main.js
> +    likes: getRandomIntNumber(15, 200),
Аналогично про 15, 200

2022-10-16 14:56 UTC, cutterror commented
исправила

2022-10-16 14:57 UTC, merged